/* Matrix Satellite Measurement v1.0
 * Property-scale aerial measurement workspace.
 * Depends on Leaflet and CactusByteGeo.
 */
(function(){
'use strict';
const state={map:null,layer:null,points:[],mode:'area',label:'Driveway',measurements:[],location:null,imagery:{provider:'Esri World Imagery',url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',attribution:'Tiles © Esri and contributors'}};
const $=id=>document.getElementById(id);
function id(){return (globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function')?globalThis.crypto.randomUUID():('m-'+Date.now()+'-'+Math.random().toString(16).slice(2));}
function init(lat,lon){if(!window.L||!window.CactusByteGeo)return false;const target=$('npSatelliteMap');if(!target)return false;state.location={lat:+lat,lon:+lon};if(!state.map){state.map=L.map(target,{zoomControl:true,attributionControl:true}).setView([lat,lon],20);L.tileLayer(state.imagery.url,{maxZoom:20,attribution:state.imagery.attribution}).addTo(state.map);state.map.on('click',e=>{state.points.push([e.latlng.lat,e.latlng.lng]);renderDraft();});}else state.map.setView([lat,lon],20);setTimeout(()=>state.map.invalidateSize(),50);render();return true;}
function renderDraft(){if(state.layer){state.map.removeLayer(state.layer);state.layer=null;}if(!state.points.length)return render();if(state.mode==='line')state.layer=L.polyline(state.points,{weight:4}).addTo(state.map);else state.layer=L.polygon(state.points,{weight:3,fillOpacity:.18}).addTo(state.map);render();}
function currentValue(){const g=window.CactusByteGeo;if(state.mode==='line')return {quantity:g.metersToFeet(g.polylineMeters(state.points)),unit:'linear_ft'};return {quantity:g.squareMetersToSquareFeet(g.polygonSquareMeters(state.points)),unit:'sq_ft'};}
function render(){const out=$('npMeasureReadout');if(out){const v=currentValue();out.textContent=state.points.length?(v.quantity.toFixed(1)+' '+(v.unit==='sq_ft'?'sq ft':'linear ft')):'Tap the map to start measuring.';}const list=$('npMeasurementList');if(list)list.innerHTML=state.measurements.length?state.measurements.map(m=>'<div class="np-sat-row"><b>'+escapeHtml(m.label)+'</b><span>'+m.quantity.toFixed(1)+' '+(m.unit==='sq_ft'?'sq ft':'linear ft')+'</span><button type="button" data-remove="'+m.id+'">×</button></div>').join(''):'<div class="np-sat-empty">No saved measurements yet.</div>';list?.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.measurements=state.measurements.filter(m=>m.id!==b.dataset.remove);render();sync();});}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function clear(){state.points=[];if(state.layer){state.map.removeLayer(state.layer);state.layer=null;}render();}
function save(){if((state.mode==='area'&&state.points.length<3)||(state.mode==='line'&&state.points.length<2))return;const v=currentValue();state.measurements.push({id:id(),label:($('npMeasureLabel')?.value||state.label).trim()||'Measured surface',kind:state.mode,quantity:v.quantity,unit:v.unit,geometry:{type:state.mode==='area'?'Polygon':'LineString',coordinates:state.points.map(p=>[+p[1],+p[0]])},evidence:{source:'aerial_manual_measurement',method:'user_traced',provider:state.imagery.provider,confidence:'measured',capturedAt:new Date().toISOString(),center:state.location}});clear();sync();}
function sync(){window.matrixSatelliteMeasurements=state.measurements.map(m=>JSON.parse(JSON.stringify(m)));window.dispatchEvent(new CustomEvent('matrix:satellite-measurements',{detail:{measurements:window.matrixSatelliteMeasurements}}));}
async function geocode(){const q=$('npPropertyAddress')?.value.trim();if(!q)return;const status=$('npGeocodeStatus');if(status)status.textContent='Finding property…';try{const r=await fetch('/api/geocode?q='+encodeURIComponent(q),{headers:{Accept:'application/json'}});const d=await r.json();if(!r.ok||!d.result)throw new Error(d.error||'Address not found');state.location={lat:d.result.lat,lon:d.result.lon,address:d.result.displayName};state.map?.setView([d.result.lat,d.result.lon],20);if(status)status.textContent=d.result.displayName||'Property found';}catch(e){if(status)status.textContent=e.message||'Could not find property';}}
function setMode(mode){state.mode=mode==='line'?'line':'area';clear();document.querySelectorAll('[data-np-measure-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.npMeasureMode===state.mode)));}
function bind(){ $('npGeocodeBtn')?.addEventListener('click',geocode);$('npMeasureUndo')?.addEventListener('click',()=>{state.points.pop();renderDraft();});$('npMeasureClear')?.addEventListener('click',clear);$('npMeasureSave')?.addEventListener('click',save);document.querySelectorAll('[data-np-measure-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.npMeasureMode)));}
window.MatrixSatelliteMeasurement={init,bind,geocode,setMode,getMeasurements:()=>state.measurements.map(m=>JSON.parse(JSON.stringify(m)))};
document.addEventListener('DOMContentLoaded',bind);
})();